➕ add prettier config
nanoutils/nanoutils pull request #237
Opened 2021-10-15 10:33 UTC by tyczynski

PR resolves #210

2021-11-08 16:49 UTC, Beraliv commented
@tyczynski I'm really sorry to make the review too long

I'm looking at it now, will provide the feedback during an hour

2021-11-08 17:09 UTC, Beraliv requested changes

2021-11-08 17:09 UTC, Beraliv commented on lib/median/index.js
> +export default (list) => {
let's revert the change for now

It will replace empty string with the function name in `SIZES.md`

2021-11-08 17:09 UTC, Beraliv commented on SIZES.md
> +|  | 130 B | 364 B | -234 B |
We should fix it here and below in `SIZES_CJS.md`

2021-11-15 18:30 UTC, tyczynski commented
@Beraliv 
Thanks for code review. I will make fixes this week :)

2022-11-18 14:32 UTC, closed without merging